### ISSUE TITLE
Function overloads for Capture and Refund methods

### ISSUE THREAD

**Issue by nibhatish** [razorpay/razorpay-dot-net#1]
Hi Team,

I have one suggestion for the Capture and Refund functions in the class - Payment. Can we create two more functions where, we can pass paymentId. This would reduce one http call for Fetch.

public Refund Refund(string paymentId)
        {
            string relativeUrl = GetEntityUrl() + "/" + paymentId + "/refund";
            List<Entity> entities = Request(relativeUrl, HttpMethod.Post, null);
            return (Refund)entities[0];
        }

```
    public Payment Capture(Dictionary<string, object> attributes,string paymentId)
    {
        string relativeUrl = GetEntityUrl() + "/" + paymentId + "/capture";
        List<Entity> entities = Request(relativeUrl, HttpMethod.Post, attributes);
        return (Payment)entities[0];
    }
```

**Comment by sunnyagg** [comment]
@nibhatish We have added a constructor in the new version of the sdk, so now you can create payment object by passing the payment_id and call capture on the object. similarly you can do same for refunds also.

This fixes the issues of extra network call.
