### ISSUE TITLE
tracking payment failures using automatic checkout

### ISSUE THREAD

**Issue by shivapr** [razorpay/razorpay-dot-net#24]
Dear Team,

Can you let me know what are parameters to target if the payment is not captured i.e. for payment failure case. I am using automatic checkout in dotnet.

**Comment by harman28** [comment]
Sorry for the delay here, noting a response anyway for anyone else who comes looking. In case of a failure on custom checkout, you'll receive payment error_code and error_description in the response. On standard checkout, failures are handled internally.
